### ISSUE TITLE
hello world? Which end is up?

### ISSUE THREAD

**Issue by dckc** [LavaMoat/LavaMoat#1]
I'm very interested to understand how you expect this to work. But I can't quite tell by looking through the tests and such what's supposed to be going on.

Here's hoping you're inspired to write a paragraph or two and add a hello world in your README.

Alternatively, I could interview you for 10 minutes by chat / screenshare / etc., write up what I learned, and submit it as a PR.

p.s. it was nice meeting you in Boulder in April, @kumavis

**Comment by kumavis** [comment]
@dckc thanks for checking in/
this work builds off of https://github.com/agoric/ses which provides the containment for the third party code. Sesify is the Trusted Computing Base that regulates which modules can talk to each other and what browser APIs are exposed to them. Would be happy to do a chat to help generate some basic documentation

**Comment by kumavis** [comment]
checkout the new introductory repos!
https://github.com/lavamoat/overview
https://github.com/lavamoat/lavamoat-browserify-examples

**Comment by dckc** [comment]
Interesting. Thanks.

In particular, via the overview, I discovered https://github.com/Agoric/SES/blob/master/docs/secure-coding-guide.md , which I had not seen.
