### ISSUE TITLE
Webpack?

### ISSUE THREAD

**Issue by hschoenburg** [LavaMoat/LavaMoat#10]
Wondering how hard it would be to port this over to be a webpack plugin?

**Comment by kumavis** [comment]
this is on the road map!

have looked into it a bit. webpack internals seem quite complicated, and the API for overriding the runtime is undocumented (but found it in the hot-module-reload code). This will need some extra fire power so let me know if you'd like to help try it out @hschoenburg

**Comment by kumavis** [comment]
made some progress, but it doesnt do the config autogeneration yet
https://github.com/lavamoat/lavamoat-webpack
