### ISSUE TITLE
[webpack] TypeError: Cannot read properties of undefined (reading 'keys')

### ISSUE THREAD

**Issue by Jack-Works** [LavaMoat/lavamoat#1221]
```
node_modules/.pnpm/@lavamoat+aa@4.2.0/node_modules/@lavamoat/aa/src/index.js:285
  const matchingPackageDirs = Array.from(canonicalNameMap.keys()).filter(
                                                          ^

TypeError: Cannot read properties of undefined (reading 'keys')
    at getPackageDirForModulePath (node_modules/.pnpm/@lavamoat+aa@4.2.0/node_modules/@lavamoat/aa/src/index.js:285:59)
    at getPackageNameForModulePath (node_modules/.pnpm/@lavamoat+aa@4.2.0/node_modules/@lavamoat/aa/src/index.js:262:22)
    at Object.inspectWebpackModule (node_modules/.pnpm/@lavamoat+webpack@0.3.0-beta.0_webpack@5.88.2/node_modules/@lavamoat/webpack/src/buildtime/policyGenerator.js:96:24)
    at node_modules/.pnpm/@lavamoat+webpack@0.3.0-beta.0_webpack@5.88.2/node_modules/@lavamoat/webpack/src/plugin.js:255:33
    at Array.forEach (<anonymous>)
    at node_modules/.pnpm/@lavamoat+webpack@0.3.0-beta.0_webpack@5.88.2/node_modules/@lavamoat/webpack/src/plugin.js:249:47
    at Array.forEach (<anonymous>)
    at node_modules/.pnpm/@lavamoat+webpack@0.3.0-beta.0_webpack@5.88.2/node_modules/@lavamoat/webpack/src/plugin.js:248:30
    at Hook.eval [as call] (eval at create (node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:14:14)
```

**Comment by Jack-Works** [comment]
sorry this still happens in @lavamoat/aa@4.3.0 for me (@lavamoat/webpack@0.4.0-beta.0). please reopen this thanks!

**Comment by legobeat** [comment]
@Jack-Works Which Node.js version are you on?

Our current understanding:

- v18 was never affected
- Issue is fixed in v22
- [v20 is pending a backport upstream](https://github.com/nodejs/node/pull/53089#issuecomment-2251964022)

**Comment by Jack-Works** [comment]
I'm using 22.2.0

**Comment by legobeat** [comment]
> I'm using 22.2.0

The bug should be fixed in Node.js v22.6.0 and later - are you able to upgrade?

Node.js maintainers just [communicated](https://github.com/nodejs/node/pull/53089#issuecomment-2282340690) we should also expect a fix in yet-unreleased v20.16.1.

**Comment by Jack-Works** [comment]
> The bug should be fixed in Node.js v22.6.0 and later - are you able to upgrade?

I think I might need to wait for a while, my PM only have 22.4.1 for now (https://search.nixos.org/packages#?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=nodejs_22)

**Comment by legobeat** [comment]
@Jack-Works FWIW this might be worth a try: https://github.com/NixOS/nixpkgs/pull/333210 (https://blog.mplanchard.com/posts/installing-a-specific-version-of-a-package-with-nix.html)

(For others: There is also a parallel open issue at #1211 pending resolution for Node.js v20.x)
