### ISSUE TITLE
License Info missing

### ISSUE THREAD

**Issue by D-Nice** [LavaMoat/LavaMoat#124]
There's no license info here, and not sure if this has to do with the MetaMask license fiasco or not. It's a cool project, but really a nonstarter for anyone to use safely from a legal perspective if it doesn't have a license.

Soruce: https://choosealicense.com/no-permission/

So would be nice to know the stance and planned roadmap of this project, or better yet just a license.

**Comment by kumavis** [comment]
missing license file added, MIT
let me know what you think of lavamoat @D-Nice
