### ISSUE TITLE
`__webpack_require__.t` is not a function

### ISSUE THREAD

**Issue by FrederikBolding** [LavaMoat/lavamoat#1307]
When using Webpack to build for the `node` target, you currently may hit the following error:
```
TypeError#1: __webpack_require__.t is not a function
  at call.__webpack_require__._LM_.__webpack_require__.__webpack_require__ (/.../dist/webpack/node-thread/bundle.js:27185:171)
```

Can be reproduced with configuration from https://github.com/MetaMask/snaps/pull/2662

**Comment by naugtur** [comment]
`__.t` turns out to be a rarely needed wrapper for module formats interop
