### ISSUE TITLE
poor diagnostic for missing config file

### ISSUE THREAD

**Issue by dckc** [LavaMoat/LavaMoat#16]
I tried a sort of hello-world scenario and when I did `npm run lavamoat` I got:

```
Error: ENOENT: no such file or directory, open './lavamoat-config.json'
```

work-around:

```
echo "{}" > lavamoat-config.json
```

**Comment by kumavis** [comment]
fixed here https://github.com/LavaMoat/lavamoat-browserify/pull/21
thanks!
