### ISSUE TITLE
docs: allow-scripts link is a 404

### ISSUE THREAD

**Issue by jzaefferer** [LavaMoat/LavaMoat#177]
Under "How to secure your app against supplychain attacks" the link for @lavamoat/allow-scripts goes to https://github.com/LavaMoat/LavaMoat/blob/main/LavamoatAllowScripts which is a 404 page (for me anyway)

I wanted to send a tiny PR to fix that directly, but the README.md actually looks fine, defining the link like this:

```md
1. disable/whitelist dependency lifecycle scripts (eg. "postinstall") via [@lavamoat/allow-scripts](LavamoatAllowScripts)
...
[LavamoatAllowScripts]: ./packages/allow-scripts
```
I see nothing wrong with that, so I don't know why this goes to the bad blog URL, instead of https://github.com/LavaMoat/LavaMoat/tree/main/packages/allow-scripts

**Comment by kumavis** [comment]
ah! for url refs it should be `[@lavamoat/allow-scripts][LavamoatAllowScripts]` thanks!

**Comment by jzaefferer** [comment]
Oh, right! I didn't notice the wrong braces 😅
