### ISSUE TITLE
docs: npx-allow-scripts instructions use old (deprecated?) package

### ISSUE THREAD

**Issue by jzaefferer** [LavaMoat/LavaMoat#178]
https://github.com/LavaMoat/LavaMoat/blob/main/packages/allow-scripts/README.md suggests to run `npx allow-scripts auto`, which would use https://github.com/dominykas/allow-scripts

I guess this should recommend to use `npx @lavamoat/allow-scripts auto`? That's not working for me either:
```
$ npx @lavamoat/allow-scripts auto
npx: installed 134 in 17.353s
Cannot find module 'resolve'
Require stack:
- /Users/jzaefferer/.npm/_npx/96060/lib/node_modules/@lavamoat/allow-scripts/src/index.js
- /Users/jzaefferer/.npm/_npx/96060/lib/node_modules/@lavamoat/allow-scripts/src/cli.js
```

**Comment by kumavis** [comment]
fixed in `main`, and enforced with `depcheck`
will publish with other enhancements

**Comment by kumavis** [comment]
"other enhancements" are still in progress so I published a patch that fixes this. should have done that sooner :pray: 

documentation updated in readme
```sh
yarn add -D @lavamoat/allow-scripts@^1.0.4
```
