### ISSUE TITLE
internalRequire:16 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by dckc** [LavaMoat/LavaMoat#18]
Any idea what I'm doing wrong?

line 16 is:

```js
var makeHardener = _interopDefault(require('@agoric/make-hardener'));
```

https://gist.github.com/dckc/2e25ba5b8baac1d8c0ec83fe77f92b68#file-reame-md

**Comment by dckc** [comment]
I get the same error with the unmodified example code (e4e2321a56d5f):

```
$ git clone git@github.com:LavaMoat/lavamoat-browserify-examples.git
Cloning into 'lavamoat-browserify-examples'...
$ cd lavamoat-browserify-examples/
lavamoat-browserify-examples$ git log -n1
commit e4e2321a56d5f...
lavamoat-browserify-examples$ cd 00-simple-cli/
lavamoat-browserify-examples/00-simple-cli$ direnv allow
direnv: using nvm 12.13.0
lavamoat-browserify-examples/00-simple-cli$ npm install
...
added 266 packages from 173 contributors and audited 1145 packages in 7.806s
lavamoat-browserify-examples/00-simple-cli$ npm start

> @ start /tmp/mm/lavamoat-browserify-examples/00-simple-cli
> browserify index.js --plugin [ lavamoat-browserify --config ./lavamoat-config.json ] > bundle.js && serve .

   │   - Local:            http://localhost:5000       │
```

open browser; in console:

```
Uncaught ReferenceError: require is not defined
    at internalRequire:16
    at internalRequire:3744
    at internalRequire:3746
    at internalRequire:4423
```

p.s. same symptoms in 01-simple-js

**Comment by kumavis** [comment]
@dckc I was able to reproduce this by using `npm install` as you did instead of my usual `yarn`

this suggests its an issue when the dependency lockfile is not used. I'll need to investigate what the underlying issue is.

**Comment by kumavis** [comment]
seems like an in-range version in `ses`'s "main" export no longer refers to the built dist, and includes a `require`

here's where we grab the `ses` source, I'll need to update it
https://github.com/LavaMoat/lavamoat-browserify/blob/fa806a2868f366bf2d518cb1e23bbc3a6c9a0afe/src/generatePrelude.js#L10

**Comment by kumavis** [comment]
it actually was not an in-range change! I'm NOT currently testing builds in the browser, and a bug broke the output but happened to work in nodejs where I actually test.

fixed here https://github.com/LavaMoat/lavamoat-browserify/commit/c02a8a9054a56b9a0a186c5f20d492f71a4f54fe

still need to actually add browser tests
