### ISSUE TITLE
documentation --ignore-scripts

### ISSUE THREAD

**Issue by wighawag** [LavaMoat/LavaMoat#186]
Hey, I have started to use `@lavamoat/allow-scripts` and `@lavamoat/preinstall-always-fail`
and it seems I need to always add `--ignore-scripts` to my yarn commands, like `yarn install` and `yarn add`
I guess because of `@lavamoat/preinstall-always-fail`, this is expected.
It might be a good idea to add some comment on the documentation.
Or maybe there is a work around to ensure that npm disable scripts by default ?

for example when calling `yarn add -D ...`
I get

```
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/9] ⠄ @lavamoat/preinstall-always-fail
[2/9] ⠄ core-js-pure
[3/9] ⠄ keccak
[4/9] ⠄ secp256k1
error C:\dev\wighawag\template-ethereum-contracts\node_modules\@lavamoat\preinstall-always-fail: Command failed.
Exit code: 1
```

**Comment by EtDu** [comment]
You can add `.yarnrc` or `.npmrc` in the project root with 
```
ignore-scripts true
```

**Comment by kumavis** [comment]
https://github.com/LavaMoat/LavaMoat/blob/main/packages/allow-scripts/README.md#disable-scripts
let us know if you have any further questions
