### ISSUE TITLE
Current status of Cytoplasm

### ISSUE THREAD

**Issue by joepie91** [LavaMoat/LavaMoat#189]
The README states:

> 3 is achieved by providing a read-only view of the imported module's exports. This read-only view is accomplished via Cytoplasm, a membrane implementation.

... but NOTES.md states:

>   - [x] kill cytoplasm (it took 8m to do a 5sec job)

and indeed I don't seem to be finding Cytoplasm used as a dependency anymore.

So... what's the current status regarding membranes? Was Cytoplasm dropped permanently for performance reasons? Will it be replaced or has it been replaced by something else, or is there currently just no exports protection?

**Comment by kumavis** [comment]
hi @joepie91 thanks for the question, yes this documentation is out of sync. currently the membrane is unused and there is no alternate moduleExports defense in place. its really hard to have a generic, performant, widely backwards compatible moduleExports defense system.

however i think there are still worthy safety features by controlling package import by policies and limiting endowments

let me know if you have any more questions, i will update the doc

**Comment by kumavis** [comment]
closing for now/
