### ISSUE TITLE
perf woes

### ISSUE THREAD

**Issue by kumavis** [LavaMoat/LavaMoat#2]
Seeing significant performance impact from current usage of SES.
I'm not very good at analyzing the performance stats, so not really sure how to improve this.

**Comment by kumavis** [comment]
Here are two "performance profiles" captured in chromium
https://gist.github.com/kumavis/382b3c1520f281778264b90b6a9c1a33

They show the initialization of a large app bundle (metamask) with vanilla browserify and with sesify.
App source was modified so all requires are processed but the app is not started. 

Bundle initialization time delta is significant:
- vanilla: 0.69s
- sesify: 5.89s

Memory usage
- vanilla: ends with js heap ~20mb
- sesify: ends with js heap ~114mb

**Comment by kumavis** [comment]
my main hypothesis for the slow down is how our module cache system works. vanilla caches everything globally and so it benefits from lots of cache hits. Sesify currently caches per module node in dependency graph, so even mutual dependencies are fresh copies. May even be "too-fresh" we re-eval everytime, but this may be necessary to handle differing endowments 
if we could have a single global cache that disallows attacker modifications and we tolerate the risk of modules communicating through mutual dependencies, this would be a performance improvement but complicates how we get developer approval when an evil dependency introduces a dependency with lots of permissions

**Comment by kumavis** [comment]
The berlin work has resolved at least the large explosion we were seeing

**Comment by erights** [comment]
AWESOME!
