### ISSUE TITLE
lint tests

### ISSUE THREAD

**Issue by kumavis** [LavaMoat/LavaMoat#202]
we should lint tests, especially to make sure we dont accidentally commit a `test.only`
https://github.com/avajs/eslint-plugin-ava

**Comment by legobeat** [comment]
Looks like this is addressed in #205?

See also: #397

**Comment by boneskull** [comment]
This can be closed, as LavaMoat uses the "recommended" config from `eslint-plugin-ava`, which restricts `only` and a [bunch of other stuff](https://github.com/avajs/eslint-plugin-ava#rules).
