### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by maebeam** [LavaMoat/LavaMoat#217]
Hello! Trying to add LavaMoat to an angular project with webpack. Do you have any guidance on what I'm doing wrong?

```
LavaMoat - Error evaluating module "src/main.ts" from package "<root>"
SyntaxError: Cannot use import statement outside a module
  at Object.eval (eval at makeEvaluateFactory (LavaMoat/node/kernel), <anonymous>:8:30)
  at performEval (LavaMoat/node/kernel:4075:14)
  at Compartment.evaluate (LavaMoat/node/kernel:5434:14)
  at prepareModuleInitializer (LavaMoat/core/kernel:572:54)
  at Object.internalRequire (LavaMoat/core/kernel:443:48)
```

I modified `index.js` to point to `main.ts`

```
const entryId = path.resolve(cwd, 'src/main.ts')
```

Webpack config:

```
const webpack = require('webpack');
const LavaMoatPlugin = require('lavamoat/src');

module.exports = (config, options, targetOptions) => {
  config.plugins.push(new webpack.NormalModuleReplacementPlugin(/^crypto$/, 'crypto-browserify'));
  config.plugins.push(new webpack.NormalModuleReplacementPlugin(/^stream$/, 'readable-stream'));
  config.plugins.push(new LavaMoatPlugin({ writeAutoConfig: true }));

  return config;
};
```

Using custom webpack builder: https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack

Let me know if you'd like me to eject and provide a full webpack configuration or other information.

Thanks in advance!

**Comment by kumavis** [comment]
hi @maebeam 
sorry the webpack plugin currently does not work. but we will prioritize it based on demain. what version of webpack are you using?
in the mean time you can still get setup with `@lavamoat/allow-scripts` and nodejs runtime `lavamoat`

**Comment by kumavis** [comment]
sorry, i realized this was not clear in the documentation -- ive added a note/warning about that

**Comment by maebeam** [comment]
@kumavis we're gonna prioritize the webpack plugin and will submit our work upstream.

based on your knowledge and rough assessment, do you foresee any major challenges getting webpack to work? the browserify plugin seems fairly straightforward.
