### ISSUE TITLE
allow-scripts fails when installing from tarball

### ISSUE THREAD

**Issue by brad-decker** [LavaMoat/LavaMoat#236]
### Description

If you use `yarn|npm pack` to create a tarball of a package then install that file using the `file:` syntax in package.json, allow-scripts fails with `failed to parse canonical name for URL: "file://..."`

Steps to reproduce:
1. run `yarn pack` in a package repository
2. move the file into another repository (optional, but easier to get the path)
3. run `yarn add file:./<filename>`
4. run `yarn allow-scripts`
5. see the error

**Comment by Gudahtt** [comment]
This can be closed in favor of #261, which is a duplicate but contains more discussion
