### ISSUE TITLE
lavamoat broken on nodejs  v20

### ISSUE THREAD

**Issue by legobeat** [LavaMoat/lavamoat#496]
CI failing on package`lavamoat` (aka lavamoat-node) on node 18+: https://github.com/LavaMoat/LavaMoat/actions/runs/4893196868/jobs/8735876501?pr=495

**Comment by legobeat** [comment]
v18 addressed in #551, pending release.
v19+ have been marked as non-supported in #552 
Current errors for v20 can be followed in #495

**Comment by naugtur** [comment]
I think this should have been closed a while ago. Is anything missing?

**Comment by boneskull** [comment]
Closed via ef3a0da9960d7f5734e3d4180ebafdae2432a260
