### ISSUE TITLE
command line tool to print out sesify config

### ISSUE THREAD

**Issue by ljharb** [LavaMoat/LavaMoat#6]
It'd be great to have a single `npx sesify-config entrypoint.js` command that spit the config JSON out to stdout.

I'm thinking about using it combined with, for example, `Object.entries(_.resources).map(([k, v]) => [k, v.globals]).filter(([, v]) => v)` to create a CI check to constrain which globals and node built-in modules my dependency graph contains.

**Comment by kumavis** [comment]
we chatted on a call about some of the limitations of this approach, but you can find docs on how to generate the config here
https://github.com/lavamoat/lavamoat-browserify-examples
