### ISSUE TITLE
lavamoat-tofu Error: unknown ast node type when trying to get name: "PrivateName"

### ISSUE THREAD

**Issue by naugtur** [LavaMoat/lavamoat#642]
happens when going through @fastify/http-proxy

Error: unknown ast node type when trying to get name: "PrivateName"
    at getNameFromNode (/app/node_modules/lavamoat-tofu/src/util.js:46:11)

**Comment by boneskull** [comment]
specifically this is in [undici](https://npm.im/undici) which uses private fields.

or at least--I _think_ this is what it's referring to.

@naugtur How to reproduce this?

**Comment by naugtur** [comment]
I installed and required the module. That was enough to trigger the error afair.
