### ISSUE TITLE
root allow-scripts config is of dubious value

### ISSUE THREAD

**Issue by boneskull** [LavaMoat/lavamoat#707]
In the root `package.json` we have a `postinstall` script which does not automatically run due to `ignore-scripts = true` in our `.npmrc`.

There's also an `allow-scripts` config that _only_ allows scripts from the root `package.json` to run.  This is invoked via `npm run setup`.

It occurs to me that if the `setup` script was just changed to whatever `postinstall` is doing, we could remove both `postinstall` and the `allow-scripts` config.

**Comment by boneskull** [comment]
@naugtur I think you mentioned this offhand in a chat we had recently

**Comment by NiteshSamuel** [comment]
Hi @boneskull, this is my first time, I just raised I PR, can have look, I work on this, 

Thank you.
