### ISSUE TITLE
policy generation: handle modern node.js module resolution

### ISSUE THREAD

**Issue by boneskull** [LavaMoat/lavamoat#763]
We should implement the following when generating policies (in rough order of importance):

1. [x] Subpath & conditional exports; probably should be considered a single issue. This is a blocker for _any_ ESM support
2. [ ] ~~Add support for `import`-as-a-`Promise`-returning-function (should happen in `lavamoat-tofu`)~~
3. [x] Add support for subpath imports 

Note that nothing in the above list is unique to ESM or CJS modules

cc @naugtur

**Comment by boneskull** [comment]
Note to self:

- File extensions are required in ESM.
- You can't `import` a `.json` file.
- The dual module hazard exists.

**Comment by boneskull** [comment]
> Subpath & conditional exports; probably should be considered a single issue. This is a blocker for any ESM support

What needed to happen here:

- Update `lavamoat-tofu` to _not_ generate imports at the "named export" level. It now works at the package level, like CJS
- Modify `lavamoat-core`'s `generatePolicy.js` to consider builtins imported via both `import` and `require`. While it's illegal to use `import` in in CJS, it _is_ legal in ESM provided you create yourself a `require` function.  I will need to verify this works as expected.  At this point in the control flow, we'd need to check the file extension and/or the closest ancestor `package.json` to determine whether or not using both was allowed.  It didn't appear this information was handy, so I didn't do anything about this for now.  This is _also_ an issue in `lavamoat-node`, and I _also_ did not implement a check here.  Maybe we can safely assume that the code we're inspecting is valid??
- Remove [`resolve`](https://npm.im/resolve) from `lavamoat-node` and use Node's builtin resolver to resolve modules. This works in both ESM and CJS contexts.  The `resolve` package does not support subpath or conditional exports, so it cannot be used.  It could still be used for CJS--@kumavis mentions that `resolve` may have been used to look at a `package.json` that was otherwise omitted from the exports--but if so, this is not obvious from the code I replaced.  At any rate, I don't think we need to worry too much about this for now. I hope.
- It's important to note that the _entry point_ of an package with an `exports` field is not necessarily a real path, but a key in the `exports` field of `package.json`.  While you may use `lavamoat -a src/index.js` in a CJS project, this would likely be incorrect in any project that has an `exports` field.  It may be worthwhile to use `exports['.']` or `main` as the default entry point, and only use something else if one is provided. In a package without `exports`, any file can be an entry point, but otherwise we're restricted to `exports` keys.  Also, if `exports` is a string, the entry point is the package name and seemingly cannot be accessed via any sort of path.
- I didn't need to pull in any special package for parsing `exports` (though I started to!), since Node's `require.resolve()` just works this out for us regardless of the module type.

**Comment by boneskull** [comment]
I'll probably want to verify, at some point, how this interacts with module loaders.  I don't know how often these are used in the wild though, and if any of our users would want or need them.

**Comment by boneskull** [comment]
We might actually get subpath imports for free, here. I'll verify that next.

**Comment by boneskull** [comment]
OK, subpath imports work. We got it for free by using `Module.createRequire()` which figures it out for us.

**Comment by boneskull** [comment]
We don't need to worry about `await import()` until ses-shim supports it.

**Comment by boneskull** [comment]
This is where I'm at:

> okay, so in the case of e.g., `{"name": "foo", "exports": "src/index.js"}` our `ResolveHook` in `lavamoat-node` breaks. you cannot resolve `foo` by anything other than the name `foo`.  but the `ResolveHook` wants to map `requestedName` to a filepath, which it cannot.  I wonder how best to determine this.
> I did run into the reason why we were using the `resolve` package.  :smile:   in `@lavamoat/aa`, we need to get at the `package.json` in order to determine its dependencies, I believe.  but that cannot be done without `resolve` if the package both a) has `exports` and b) does not export `package.json`.  right now, what I have is a thing that tries the "real" `require.resolve` then falls back to `resolve` if that doesn't work.  there are other, generally worse ways to determine the dependencies of a given package on disk, though (e.g., `npm explain`)

**Comment by boneskull** [comment]
Need to add some more parsing around global detection and treating `export * from 'foo'` as an _import_

**Comment by kumavis** [comment]
we might just want to write something special for loading `package.json` if necessary.

need to verify these changes are compatible with metamask's use of LavaMoat or if it's use can be adjusted to retain compatibility

**Comment by boneskull** [comment]
@naugtur I have policy gen for ESM packages working decently [in my branch](https://github.com/lavamoat/lavamoat/tree/boneskull/lavamoat-node-esm).  No `await import()` until it's implemented in Endo though. We can use the output in our test fixtures for endomoat

**Comment by boneskull** [comment]
This is working in #772 insofar as it can work w/ the current limitations of SES.
